export const blogPosts = [
  { id: 1, title: '10 Mẹo Học Từ Vựng Tiếng Anh Hiệu Quả', excerpt: 'Khám phá những phương pháp học từ vựng tiếng Anh hiệu quả nhất để cải thiện vốn từ nhanh chóng và bền vững.', content: 'Học từ vựng tiếng Anh là một trong những thách thức lớn nhất khi học ngôn ngữ này. Trong bài viết này, chúng ta sẽ khám phá 10 mẹo học từ vựng hiệu quả nhất với ví dụ thực tế và lộ trình áp dụng hàng ngày...', author: 'VocaType Team', date: '2024-01-15', category: 'Học tập', tags: ['từ vựng','tiếng anh','học tập'], readTime: '5 phút', views: 1250, likes: 89, comments: 23, image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=675&fit=crop' },
  { id: 2, title: 'Luyện Gõ Phím: Từ Cơ Bản Đến Nâng Cao', excerpt: 'Hướng dẫn chi tiết cách luyện gõ phím từ những bước đầu tiên đến khi thành thạo.', content: 'Gõ phím nhanh và chính xác là kỹ năng quan trọng. Bài viết tổng hợp các bài tập theo cấp độ, mẹo đặt tay, cách theo dõi tiến bộ cùng bộ bài tập 14 ngày...', author: 'VocaType Team', date: '2024-01-12', category: 'Kỹ năng', tags: ['gõ phím','kỹ năng','luyện tập'], readTime: '7 phút', views: 980, likes: 67, comments: 15, image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&h=675&fit=crop' },
  { id: 3, title: 'Cách Tạo Đề Thi Trắc Nghiệm Hiệu Quả', excerpt: 'Nguyên tắc và kỹ thuật để tạo ra câu hỏi trắc nghiệm chất lượng.', content: 'Đề thi trắc nghiệm hiệu quả cần rõ ràng, phân loại được năng lực. Bài viết đưa ra 12 nguyên tắc vàng và checklist khi soạn đề...', author: 'VocaType Team', date: '2024-01-10', category: 'Giáo dục', tags: ['đề thi','trắc nghiệm','giáo dục'], readTime: '6 phút', views: 756, likes: 45, comments: 12, image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=675&fit=crop' },
  { id: 4, title: 'Tâm Lý Học Trong Việc Học Ngôn Ngữ', excerpt: 'Yếu tố tâm lý ảnh hưởng đến quá trình học ngôn ngữ và cách tối ưu.', content: 'Động lực, sự tự tin, nỗi sợ sai ảnh hưởng mạnh đến hiệu suất học. Bài viết phân tích các cơ chế tâm lý và cách áp dụng vào luyện tập hàng ngày...', author: 'VocaType Team', date: '2024-01-08', category: 'Tâm lý', tags: ['tâm lý','học tập','ngôn ngữ'], readTime: '8 phút', views: 634, likes: 38, comments: 8, image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=675&fit=crop' }
];

export const getPostById = (id) => blogPosts.find(p => String(p.id) === String(id));


